import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { http } from '../lib/api';
import { Navbar } from '../components/Navbar';
import { Footer } from '../components/Footer';

const FILTERS = ['All', 'Kindergarten', 'Primary', 'Secondary', 'IELTS'];

export default function PublicLibrary() {
  const [worksheets, setWorksheets] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [activeFilter, setActiveFilter] = useState('All');

  useEffect(() => {
    const fetchLibrary = async () => {
      setLoading(true);
      setError('');
      try {
        // Use shared axios http instance - not raw fetch()
        // Raw fetch() does not send credentials (cookies) by default
        const params = activeFilter !== 'All' ? { level: activeFilter } : {};
        const r = await http.get('/library/feed', { params });
        setWorksheets(r.data);
      } catch (err) {
        setError('Failed to load the library. Please try again.');
        console.error('Library fetch error:', err);
      } finally {
        setLoading(false);
      }
    };
    fetchLibrary();
  }, [activeFilter]);

  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      <main className="flex-1 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 font-sans w-full">

        <div className="text-center mb-16">
          <h1 className="text-4xl md:text-5xl font-extrabold text-gray-900 mb-4">
            The <span className="text-red-600">Community</span> Library
          </h1>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto font-medium">
            Browse, preview, and print free ESL worksheets generated by teachers across Vietnam.
          </p>
        </div>

        {/* Level filters */}
        <div className="flex flex-wrap justify-center gap-3 mb-12">
          {FILTERS.map((filter) => (
            <button
              key={filter}
              onClick={() => setActiveFilter(filter)}
              className={`px-6 py-2 rounded-full font-bold text-sm transition-all shadow-sm ${
                activeFilter === filter
                  ? 'bg-black text-white'
                  : 'bg-white text-gray-600 border border-gray-200 hover:border-black hover:text-black'
              }`}
            >
              {filter}
            </button>
          ))}
        </div>

        {loading ? (
          <div className="flex justify-center items-center py-20">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-red-600"></div>
          </div>
        ) : error ? (
          <div className="text-center py-20 text-red-600 font-bold bg-red-50 rounded-2xl border border-red-100 max-w-2xl mx-auto p-8">
            {error}
          </div>
        ) : worksheets.length === 0 ? (
          <div className="text-center py-20 text-gray-500 font-medium bg-gray-50 rounded-2xl border border-gray-200 max-w-2xl mx-auto p-8">
            <div className="text-4xl mb-4">📚</div>
            <p>No public worksheets found for this level yet.</p>
            <Link to="/dashboard" className="mt-4 inline-block text-red-600 font-bold hover:underline">
              Be the first to generate one →
            </Link>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {worksheets.map((ws) => (
              <div
                key={ws.worksheet_id}
                className="bg-white rounded-2xl border border-gray-200 shadow-sm hover:shadow-xl transition-all flex flex-col overflow-hidden group"
              >
                <div className="p-6 flex-grow">
                  <div className="flex justify-between items-start mb-4">
                    <span className="bg-red-50 text-red-700 text-xs font-black px-3 py-1 rounded-full uppercase tracking-wide">
                      {ws.level}
                    </span>
                    <span className="text-xs font-bold text-gray-400 uppercase tracking-widest">
                      {ws.cefr}
                    </span>
                  </div>
                  <h3 className="text-xl font-bold text-gray-900 mb-2 line-clamp-2 group-hover:text-red-600 transition-colors">
                    {ws.title}
                  </h3>
                  <div className="flex flex-wrap gap-2 mt-4">
                    <span className="bg-gray-100 text-gray-600 text-xs font-semibold px-2 py-1 rounded">
                      {ws.skill}
                    </span>
                    <span className="bg-gray-100 text-gray-600 text-xs font-semibold px-2 py-1 rounded truncate max-w-full">
                      {ws.topic}
                    </span>
                  </div>
                </div>
                <div className="p-4 border-t border-gray-100 bg-gray-50">
                  <Link
                    to={`/worksheet/${ws.worksheet_id}`}
                    className="w-full flex justify-center items-center bg-white border-2 border-black text-black font-bold py-3 rounded-xl hover:bg-black hover:text-white transition-colors"
                  >
                    👀 Preview &amp; Print
                  </Link>
                </div>
              </div>
            ))}
          </div>
        )}
      </main>
      <Footer />
    </div>
  );
}
