import React from 'react';
import { useI18n } from '../lib/i18n';
import { PageShell } from '../components/PageShell';

export default function Terms() {
  const { lang } = useI18n();
  const en = (
    <>
      <h2 className="font-display text-3xl mt-8">1. The agreement</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">By using SmartGiaoAn you accept these terms. If you don\u2019t accept them, please don\u2019t use the service.</p>
      <h2 className="font-display text-3xl mt-8">2. Acceptable use</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">Use SmartGiaoAn for educational worksheet generation. Do not use it to produce hateful, sexual, violent, illegal, or politically inflammatory content. Do not attempt to reverse-engineer the service or scrape it programmatically.</p>
      <h2 className="font-display text-3xl mt-8">3. Free and paid plans</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">Free plan: 3 worksheets per browser, plus extra credits earned via rewarded ads. Premium plan: £5/month via PayPal, billed monthly, cancellable any time in your PayPal account. No refunds for partial months.</p>
      <h2 className="font-display text-3xl mt-8">4. Content ownership</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">You own the worksheets you generate and may use them in your classroom freely. You may not resell raw worksheet output as a product or distribute the SmartGiaoAn service white-labelled.</p>
      <h2 className="font-display text-3xl mt-8">5. AI disclaimer</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">Worksheets are generated by AI. We strive for accuracy but cannot guarantee every answer key is perfect. Always review before classroom use.</p>
      <h2 className="font-display text-3xl mt-8">6. Liability</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">Service provided "as is". We are not liable for indirect or consequential damages. Total liability is capped at fees paid in the prior 12 months.</p>
      <h2 className="font-display text-3xl mt-8">7. Termination</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">You can stop using the service any time. We may suspend accounts that violate acceptable use.</p>
      <h2 className="font-display text-3xl mt-8">8. Governing law</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">These terms are governed by the laws of England & Wales.</p>
    </>
  );
  const vi = (
    <>
      <h2 className="font-display text-3xl mt-8">1. Thoả thuận</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">Bằng việc dùng SmartGiaoAn, bạn chấp nhận các điều khoản này. Nếu không, vui lòng không dùng dịch vụ.</p>
      <h2 className="font-display text-3xl mt-8">2. Sử dụng phù hợp</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">Dùng SmartGiaoAn cho mục đích tạo bài tập giáo dục. Không tạo nội dung thù ghét, khiêu dâm, bạo lực, vi phạm pháp luật. Không reverse-engineer hoặc scrape dịch vụ.</p>
      <h2 className="font-display text-3xl mt-8">3. Gói miễn phí và trả phí</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">Miễn phí: 3 bài/trình duyệt, cộng credit thêm từ QC. Premium: £5/tháng qua PayPal, thanh toán hàng tháng, có thể huỷ bất kỳ lúc nào trong PayPal. Không hoàn tiền cho tháng dùng dở.</p>
      <h2 className="font-display text-3xl mt-8">4. Quyền sở hữu nội dung</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">Bạn sở hữu bài tập đã tạo và dùng tự do trong lớp. Không được bán lại nguyên gốc hoặc phân phối dịch vụ dưới thương hiệu khác.</p>
      <h2 className="font-display text-3xl mt-8">5. Tuyên bố về AI</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">Bài tập do AI tạo. Chúng tôi cố gắng chính xác nhưng không đảm bảo mọi đáp án đều hoàn hảo. Vui lòng kiểm tra trước khi dạy.</p>
      <h2 className="font-display text-3xl mt-8">6. Trách nhiệm</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">Dịch vụ cung cấp "nguyên trạng". Chúng tôi không chịu trách nhiệm thiệt hại gián tiếp. Tổng trách nhiệm giới hạn ở phí đã trả trong 12 tháng gần nhất.</p>
      <h2 className="font-display text-3xl mt-8">7. Chấm dứt</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">Bạn có thể ngừng dùng bất kỳ lúc nào. Chúng tôi có thể tạm khoá tài khoản vi phạm.</p>
      <h2 className="font-display text-3xl mt-8">8. Luật áp dụng</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">Điều khoản này điều chỉnh bởi luật pháp Anh & Xứ Wales.</p>
    </>
  );
  return (
    <PageShell
      eyebrow={lang === 'vi' ? 'Pháp lý' : 'Legal'}
      title={lang === 'vi' ? 'Điều khoản sử dụng' : 'Terms of service'}
      intro={lang === 'vi' ? 'Cập nhật lần cuối: tháng 2/2026.' : 'Last updated: February 2026.'}
    >
      <article className="max-w-3xl">{lang === 'vi' ? vi : en}</article>
    </PageShell>
  );
}
